[package]
name = "read_pdf_417"
version = "0.1.0"
authors = ["Ayrton Sparling <ayrton@sparling.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.10"
